# Generated by Django 4.2.27 on 2026-01-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='spotify_link',
            field=models.URLField(blank=True, help_text='Pega aquí el enlace de la canción (Compartir > Copiar enlace de canción)', max_length=500, null=True, verbose_name='Enlace de Spotify'),
        ),
    ]
