# Generated by Django 4.2.27 on 2026-01-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_spotify_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gratitude',
            field=models.TextField(blank=True, null=True, verbose_name='¿Por qué estás más agradecido en tu vida?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='happy_memory',
            field=models.TextField(blank=True, null=True, verbose_name='¿Cuál es tu recuerdo más feliz?'),
        ),
    ]
