# Generated by Django 4.2.27 on 2026-01-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_gratitude_userprofile_happy_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_place',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lugar favorito'),
        ),
    ]
