# Generated by Django 4.2.27 on 2026-03-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_favorite_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_place',
            field=models.CharField(blank=True, db_column='favorite_place', max_length=255, null=True, verbose_name='Lugar favorito'),
        ),
    ]
