# Generated by Django 4.2.27 on 2026-02-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classgroup',
            name='invite_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Código de invitación'),
        ),
    ]
