# Generated by Django 5.2.3 on 2025-07-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_userresult_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='category',
            field=models.CharField(choices=[('V', 'Visual'), ('A', 'Actos de servicio'), ('R', 'Recibir regalos'), ('K', 'Kinesthetic'), ('P', 'Palabras de afirmación'), ('T', 'Tiempo de calidad'), ('C', 'Toque físico')], max_length=1),
        ),
        migrations.AlterField(
            model_name='userresult',
            name='dominant_category',
            field=models.CharField(choices=[('V', 'Visual'), ('A', 'Actos de servicio'), ('R', 'Recibir regalos'), ('K', 'Kinesthetic'), ('P', 'Palabras de afirmación'), ('T', 'Tiempo de calidad'), ('C', 'Toque físico')], max_length=1),
        ),
    ]
