# Generated by Django 5.2.3 on 2026-01-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_reset_option_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='category',
            field=models.CharField(choices=[('V', 'Visual'), ('A', 'Palabras de Afirmación'), ('R', 'Read/Write'), ('K', 'Kinesthetic'), ('B', 'Tiempo de Calidad'), ('C', 'Recibir Detalles o Regalos'), ('D', 'Actos de Servicio'), ('E', 'Contacto o Presencia Física y Emocional')], max_length=1),
        ),
        migrations.AlterField(
            model_name='option',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userresult',
            name='dominant_category',
            field=models.CharField(choices=[('V', 'Visual'), ('A', 'Palabras de Afirmación'), ('R', 'Read/Write'), ('K', 'Kinesthetic'), ('B', 'Tiempo de Calidad'), ('C', 'Recibir Detalles o Regalos'), ('D', 'Actos de Servicio'), ('E', 'Contacto o Presencia Física y Emocional')], max_length=1),
        ),
    ]
